---
title: "Identifying risky bank loans using C5.0 decision trees"
date: '`r format(Sys.time(), "%B %d, %Y")`'
output: github_document
---


```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Information
* 数据获取 https://github.com/stedy/Machine-Learning-with-R-datasets
* R markdown整理 https://github.com/yi1873/machine_learning

## Step 1. Prepare data

* 读取数据
```{r, eval=T, echo = T, tidy = TRUE, size="small", cache=FALSE, warning=FALSE}
credit <- read.csv("../data/credit.csv")

str(credit)
```

* Creating random training and test datasets
```{r, eval=T, echo = T, tidy = TRUE, size="small", cache=FALSE, warning=FALSE}
set.seed(123) 
train_sample <- sample(1000, 900)
str(train_sample)

credit_train <- credit[train_sample, ] 
credit_test <- credit[-train_sample, ]

credit_train$default<-as.factor(credit_train$default)

prop.table(table(credit_train$default))
prop.table(table(credit_test$default))

```

## Step 2. Training a model on the data
```{r, eval=T, echo = T, tidy = TRUE, size="small", cache=FALSE, warning=FALSE}
library(C50)

credit_model <- C5.0(credit_train[-17], credit_train$default)

credit_model

summary(credit_model)
```

## Step 3. Evaluating model performance
```{r, eval=T, echo = T, tidy = TRUE, size="small", cache=FALSE, warning=FALSE}
credit_pred <- predict(credit_model, credit_test)
library(gmodels) 
CrossTable(credit_test$default, credit_pred, prop.chisq = FALSE, 
           prop.c = FALSE, prop.r = FALSE, dnn = c('actual default', 'predicted default'))

```

## Step 4. Improving model performance

* Boosting the accuracy of decision trees
```{r, eval=T, echo = T, tidy = TRUE, size="small", cache=FALSE, warning=FALSE}
credit_boost10 <- C5.0(credit_train[-17], credit_train$default, trials = 10)

credit_boost10

summary(credit_boost10)

credit_boost_pred10 <- predict(credit_boost10, credit_test) 
CrossTable(credit_test$default, credit_boost_pred10, prop.chisq = FALSE, prop.c = FALSE, 
           prop.r = FALSE, dnn = c('actual default', 'predicted default'))
```


