---
title: "Performing OCR with SVMs"
date: '`r format(Sys.time(), "%B %d, %Y")`'
output: github_document
---

```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Information
* 数据获取 https://github.com/stedy/Machine-Learning-with-R-datasets
* R markdown整理 https://github.com/yi1873/machine_learning

## Step 1. Prepare data

* 读取数据
```{r, eval=T, echo = T, tidy = TRUE, size="small", cache=FALSE, warning=FALSE}
letters <- read.csv("../data/letterdata.csv")

str(letters)
```

## Step 2. Training a model on the data
```{r, eval=T, echo = T, fig.align = 'center', fig.height = 6, fig.width = 5, out.width="90%",  cache=FALSE, fig.cap="Fig 1. Neural Network model", warning=FALSE}
library(kernlab)

letters_train <- letters[1:16000, ] 
letters_test <- letters[16001:20000, ]

letter_classifier <- ksvm(letter ~ ., data = letters_train, kernel = "vanilladot")
letter_classifier
```

## Step 3. Evaluating model performance
```{r, eval=T, echo = T, tidy = TRUE, size="small", cache=FALSE, warning=FALSE}
letter_predictions <- predict(letter_classifier, letters_test)
table(letter_predictions, letters_test$letter)

agreement <- letter_predictions == letters_test$letter
table(agreement)
prop.table(table(agreement))
```

## Step 4. Improving model performance
```{r, eval=T, echo = T, tidy = TRUE, size="small", cache=FALSE, warning=FALSE}
letter_classifier_rbf <- ksvm(letter ~ ., data = letters_train, kernel = "rbfdot")
letter_predictions_rbf <- predict(letter_classifier_rbf, letters_test)
agreement_rbf <- letter_predictions_rbf == letters_test$letter
table(agreement_rbf)
prop.table(table(agreement_rbf))
```


