---
title: "Finding teen market segments using k-means clustering"
date: '`r format(Sys.time(), "%B %d, %Y")`'
output: github_document
---

```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Information
* 数据获取 https://github.com/stedy/Machine-Learning-with-R-datasets
* R markdown整理 https://github.com/yi1873/machine_learning

## Step 1. Prepare data

* 读取数据
```{r, eval=T, echo = T, tidy = TRUE, size="small", cache=FALSE, warning=FALSE}
teens <- read.csv("../data/snsdata.csv")
str(teens)
table(teens$gender)
table(teens$gender, useNA = "ifany")
teens$age <- ifelse(teens$age >= 13 & teens$age < 20, teens$age, NA)
summary(teens$age)
```

## Step 2. Data preparation  
* dummy coding missing values
```{r, eval=T, echo = T, tidy = TRUE, size="small", cache=FALSE, warning=FALSE}
teens$female <- ifelse(teens$gender == "F" & !is.na(teens$gender), 1, 0)
teens$no_gender <- ifelse(is.na(teens$gender), 1, 0)
table(teens$gender, useNA = "ifany")
table(teens$female, useNA = "ifany")
table(teens$no_gender, useNA = "ifany")
```

* imputing the missing values
```{r, eval=T, echo = T, tidy = TRUE, size="small", cache=FALSE, warning=FALSE}
mean(teens$age, na.rm = TRUE)
aggregate(data = teens, age ~ gradyear, mean, na.rm = TRUE)
ave_age <- ave(teens$age, teens$gradyear, FUN = function(x) mean(x, na.rm = TRUE))
teens$age <- ifelse(is.na(teens$age), ave_age, teens$age)
summary(teens$age)
```

## Step 3. Training a model on the data
```{r, eval=T, echo = T, tidy = TRUE, size="small", cache=FALSE, warning=FALSE}
library(stats)
interests <- teens[5:40]
interests_z <- as.data.frame(lapply(interests, scale))
set.seed(2345)
teen_clusters <- kmeans(interests_z, 5)
```

## Step 4. Eevaluating model performance
```{r, eval=T, echo = T, tidy = TRUE, size="small", cache=FALSE, warning=FALSE}
teen_clusters$size
teen_clusters$centers
```

## Step 5. Improving model performance
```{r, eval=T, echo = T, tidy = TRUE, size="small", cache=FALSE, warning=FALSE}
teens$cluster <- teen_clusters$cluster
teens[1:5, c("cluster", "gender", "age", "friends")]
aggregate(data = teens, age ~ cluster, mean)
aggregate(data = teens, female ~ cluster, mean)
aggregate(data = teens, friends ~ cluster, mean)

```


