---
title: "Neural Network: Modeling the strength of concrete with ANNs"
date: '`r format(Sys.time(), "%B %d, %Y")`'
output: github_document
---

```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Information
* 数据获取 https://github.com/stedy/Machine-Learning-with-R-datasets
* R markdown整理 https://github.com/yi1873/machine_learning

## Step 1. Prepare data

* 读取数据
```{r, eval=T, echo = T, tidy = TRUE, size="small", cache=FALSE, warning=FALSE}
concrete <- read.csv("../data/concrete.csv")

str(concrete)

normalize <- function(x){ 
  return((x - min(x)) / (max(x) - min(x))) 
}
concrete_norm <- as.data.frame(lapply(concrete, normalize))
summary(concrete_norm$strength) 
summary(concrete$strength)
```

## Step 2. Training a model on the data
```{r, eval=T, echo = T, fig.align = 'center', fig.height = 6, fig.width = 5, out.width="90%",  cache=FALSE, fig.cap="Fig 1. Neural Network model", warning=FALSE}
library(neuralnet)

concrete_train <- concrete_norm[1:773, ] 
concrete_test <- concrete_norm[774:1030, ]

concrete_model <- neuralnet(strength ~ cement + slag + ash + water + superplastic + coarseagg + fineagg + age, data=concrete_train)

plot(concrete_model)
```

```{r,eval=T,echo=F,fig.align = 'center', fig.height = 18, fig.width = 18, out.width="90%", fig.showtext = T, cache=FALSE, fig.cap="Fig 1. Neural network model"}
library(png)
library(grid)
library(gridExtra)
img1 <- rasterGrob(as.raster(readPNG(paste0("plot/neural_network.1.png"))), interpolate = FALSE)
grid.newpage()
grid.arrange(img1, ncol = 1)
``` 


## Step 3. Evaluating model performance
```{r, eval=T, echo = T, tidy = TRUE, size="small", cache=FALSE, warning=FALSE}
model_results <- compute(concrete_model, concrete_test[1:8])
predicted_strength <- model_results$net.result
cor(predicted_strength, concrete_test$strength)
```

## Step 4. Improving model performance
```{r, eval=T, echo = T, tidy = TRUE, size="small", cache=FALSE, warning=FALSE}
concrete_model2 <- neuralnet(strength ~ cement + slag + ash + water + superplastic + coarseagg + fineagg + age, data = concrete_train, hidden = 5)
plot(concrete_model2)
```

```{r,eval=T,echo=F,fig.align = 'center', fig.height = 18, fig.width = 18, out.width="90%", fig.showtext = T, cache=FALSE, fig.cap="Fig 2. Improved model"}
library(png)
library(grid)
library(gridExtra)
img2 <- rasterGrob(as.raster(readPNG(paste0("plot/neural_network.2.png"))), interpolate = FALSE)
grid.arrange(img2, ncol = 1)
  
```

```{r,eval=T,echo=T}
model_results2 <- compute(concrete_model2, concrete_test[1:8]) 
predicted_strength2 <- model_results2$net.result 
cor(predicted_strength2, concrete_test$strength)
```


